[build]
builder = "nixpacks"
buildCommand = "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[deploy]
preDeployCommand = ["python3 manage.py migrate --noinput"]
startCommand = "gunicorn catSite.wsgi:application --bind 0.0.0.0:8000"

[env]
PORT = "8000"
DJANGO_SETTINGS_MODULE = "catSite.settings"
PYTHONUNBUFFERED = "1"