[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmds = ["python3 manage.py migrate && gunicorn catSite.wsgi --bind 0.0.0.0:$PORT"]