[build]
builder = "nixpacks"
buildCommand = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "python3 manage.py migrate && gunicorn catSite.wsgi:application"
